{{- if .Values.kubecostChecks -}}
{{- if .Values.kubecostChecks.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cost-analyzer-checks
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
spec:
  {{- if .Values.kubecostChecks.debug }}
  schedule: "*/1 * * * *"
  {{- else }}
  schedule: "*/10 * * * *"
  {{- end }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cost-analyzer-checks
          {{- if .Values.kubecostChecks }}
            image: {{ .Values.kubecostChecks.image }}:prod-{{ $.Chart.AppVersion }}
          {{- else }}
            image: ajaytripathy/kubecost-checks:prod-{{ $.Chart.AppVersion }}
          {{ end }}
            imagePullPolicy: Always
            args:
            - node
            - ./node/cron.js
            resources:
{{ toYaml .Values.kubecostChecks.resources | indent 14 }}
            env:
            - name: COST_ANALYZER_SERVER_ENDPOINT
              value: {{ template "cost-analyzer.fullname" . }}.{{ .Release.Namespace  }}:9001
            - name: COST_ANALYZER_MODEL_ENDPOINT
              value: {{ template "cost-analyzer.fullname" . }}.{{ .Release.Namespace  }}:9003
            {{- if .Values.kubecostChecks }}
            {{- if .Values.kubecostChecks.debug }}
            - name: SEND_UPDATES_NOW
              value: "true"
            {{- end }}
            {{- end }}
            - name: PROMETHEUS_ALERTMANAGER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "cost-analyzer.fullname" . }}
                  key: prometheus-alertmanager-endpoint
          restartPolicy: OnFailure
{{- end -}}
{{- end -}}